### ISSUE TITLE
latest release is old

### ISSUE THREAD

**Issue by ausfestivus** [Azure/terraform-azurerm-postgresql#16]
Is it just me or is the latest release/tag in this repo a long way behind what's currently available in the master branch?

Latest release/tag is 1.4 on Oct 2018.
PR #13 and #14 have been merged since that time.

Ping @echuvyrov

**Comment by michaelbiriley** [comment]
Lets get master moved to a new release.

**Comment by ausfestivus** [comment]
I don't think anyone is home. Let's poke a few of the contributors.

@logachev 
@stuartleeks 
@microsoftopensource 
@echuvyrov 
@msftgits 
@dcaro

**Comment by boldandbusted** [comment]
So, is this module abandonware? Strange, since it has the blue "Validated" checkmark in the Terraform Public Registry. :( Cheers.

**Comment by ausfestivus** [comment]
Ive noticed that most of the verified Azure modules seem to be mostly abandoned. Ill bounce it up the Hashicorp and MS food chain via our SEs and see what happens.

**Comment by manoatsas** [comment]
any update on this? or is this project abandoned since it's no longer usable with terraform latest (v0.12.24)

**Comment by logachev** [comment]
I'm really sorry for this, seems like notifications from this repo just drowned in my inbox due to other projects notifications.
I will take a look this week.
I'll also follow up internally to figure out an owner for this moving forward.

**Comment by atrauzzi** [comment]
How did this happen?

I really hope that this isn't because postgres is a competitor to MSSQL.  MS has a really bad history to escape when it comes to bitter database rivalry.

The fact is, MSSQL is just not well supported enough in every ecosystem to warrant having it get better attention than postgres.

Can we get an updated provider published right away that matches the documentation?  We are creating deployment scripts for real Azure services and this is 100% blocking us.

**Comment by ausfestivus** [comment]
Any updates @logachev?

**Comment by yupwei68** [comment]
Hi @ausfestivus Thanks for opening this issue. Sorry for the delayed reply. Currently, we have release 2.0.0 to fit in Terraform 0.12. Please try it if you would like. And sorry that I have to close this issue. If you have anything unclear, don't hesitate to reopen this issue.
